name: Cardio2e
description: Bridge between Secant Cardio2e home automation (RS-232) and Home Assistant via MQTT
version: "1.0.7"
slug: cardio2e
url: https://github.com/fapgomes/hassio-cardio2e
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
uart: true
options:
  serial_port: /dev/ttyUSB0
  baudrate: 9600
  password: "00000"
  debug: false
  update_date_interval: 3600
  ha_discover_prefix: homeassistant
  fetch_light_names: true
  dimmer_lights: ""
  force_include_lights: ""
  fetch_switch_names: true
  fetch_cover_names: true
  skip_init_cover_state: false
  ncovers: 20
  fetch_names_hvac: true
  alarm_code: 12345
  fetch_zone_names: true
  zones_normal_as_off: ""
  syslog_address: ""
  syslog_port: 514
  mqtt_address: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
schema:
  serial_port: str
  baudrate: int
  password: str
  debug: bool
  update_date_interval: int
  ha_discover_prefix: str
  fetch_light_names: bool
  dimmer_lights: "str?"
  force_include_lights: "str?"
  fetch_switch_names: bool
  fetch_cover_names: bool
  skip_init_cover_state: bool
  ncovers: int
  fetch_names_hvac: bool
  alarm_code: int
  fetch_zone_names: bool
  zones_normal_as_off: "str?"
  syslog_address: "str?"
  syslog_port: int
  mqtt_address: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
